version: '3'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: library_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d library_db" ]
      interval: 10s
      timeout: 5s
      retries: 10

  api:
    build: ./library_back
    environment:
      - POSTGRES_DB=library_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - api:/api

  app:
    build: ./library_front
    environment:
      - REACT_APP_API_URL=http://api:8000
    ports:
      - 3000:3000
    depends_on:
      - api
      - db
    volumes:
      - app:/app

  nginx:
    image: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/
    depends_on:
      - api

volumes:
  db:
    driver: local
  api:
  app:


