version: '3'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: library_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - db://var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d library_db" ]
      interval: 10s
      timeout: 5s
      retries: 10
  api:
    build: ./library_back
    ports:
      - 8010:8000
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - api://api

volumes:
  db:
    driver: local
  api:


