version: '3'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: library_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - db://var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  db:
    driver: local