name: Build and test workflow

on:
  push:
    branches: ["main", "teste-ci"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v3

      - name: Build containers
        run: |
          docker-compose build

      - name: Start containers
        run: |
          docker-compose up -d

      - name: Test verify all containers run
        run: |
          docker ps

      - name: Down containers
        run: |
          docker-compose down
  test-js:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node 14
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install Dependencies
        run: |
          cd library_front
          npm install

      - name: Run tests
        run: |
          cd library_front
          npm test
  test-py:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: |
          cd library_back
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          cd library_back
          python manage.py test