name: Django CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v3

      - name: Start db
        run: |
          docker-compose up -d db

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          cd library_back
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        env:
          POSTGRES_DB: library_db
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
        run: |
          cd library_back
          python manage.py test

      - name: Down containers
        run: |
          docker-compose down
