name: Docker-compose execution

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v3

      - name: Start containers
        run: |
          docker-compose up -d

      - name: Test verify all containers run
        run: |
          docker ps

      - name: Down containers
        run: |
          docker-compose down
